import { ConfigModel } from "./config.model";
import { EmpresaModel } from "../common/empresa.model";
import { PerfilModel } from "./perfil.model";

export class UsuarioModel {
	usuarioID: number;
	empresaID: number;
	empresaNombre: string;
	usuarioIDReferencia: number;
	usuarioTipoID: number;
	usuarioTipoNombre: string;
	usuarioCodigo: string;
	usuarioLegajo: string;
	usuarioDNI: string;
	usuarioNombreCompleto: string;
	usuarioCorreo: string;
	usuarioTelefono: string;
	usuarioWeb: boolean;
	usuarioWebID: number;
	usuarioWebLogin: string;
	usuarioWebPassword: string;
	usuarioWPass: string;
	webEstadoID: number;
	usuarioWebStatus: boolean;
	usuarioMovil: boolean;
	usuarioMovilID: number;
	usuarioMovilLogin: string;
	usuarioMovilPassword: string;
	usuarioMPass: string;
	movilEstadoID: number;
	usuarioMovilStatus: boolean;
	usuarioEstado: string;
	usuarioStatus: boolean;
	usuarioLogin: string;
	movilBacoID: number[];
	movilBacoCod: String;
	movilCAEID: number[];
	movilCAECod: string;
	movilAcopioComedorID: number[];
	movilAcopioComedorCod: string;
	disabled: boolean;
	usuarioEmpresas: EmpresaModel[];
	detallePerfilesWeb: PerfilModel[];
	detallePerfilesMovil: PerfilModel[];
	detalleConfiguraciones: ConfigModel[];
	login: string;
	usuarioWebPerfiles: any[];
	perfilWebID?: number;
	perfilWebDescripcion?: string;
	areaID: number;

	clear() {
		this.usuarioID = 0;
		this.empresaID = 0;
		this.empresaNombre = "";
		this.usuarioIDReferencia = 0;
		this.usuarioTipoID = 0;
		this.usuarioTipoNombre = "";
		this.usuarioCodigo = "";
		this.usuarioLegajo = "";
		this.usuarioDNI = "";
		this.usuarioNombreCompleto = "";
		this.usuarioCorreo = "";
		this.usuarioWeb = false;
		this.usuarioWebID = 0;
		this.usuarioWebLogin = "";
		this.usuarioWebPassword = "";
		this.usuarioWebStatus = true;
		this.webEstadoID = 1;
		this.usuarioMovil = false;
		this.usuarioMovilID = 0;
		this.usuarioMovilLogin = "";
		this.usuarioMovilPassword = "";
		this.usuarioMovilStatus = true;
		this.movilEstadoID = 1;
		this.usuarioStatus = true;
		this.usuarioEstado = "";
		this.usuarioLogin = "";
		this.movilBacoID = [];
		this.movilBacoCod = "";
		this.movilCAEID = [];
		this.movilCAECod = "";
		this.movilAcopioComedorID = [];
		this.movilAcopioComedorCod = "";
		this.disabled = false;
		this.usuarioEmpresas = [];
		this.detallePerfilesWeb = [];
		this.detallePerfilesMovil = [];
		this.detalleConfiguraciones = [];
		this.usuarioWebPerfiles = [];
		this.perfilWebID = 0;
		this.perfilWebDescripcion = "";
		this.areaID = 0;
	}
}
